name: hiercadnet
channels:
        - defaults
        - conda-forge
dependencies:
        - python=3.8
        - numpy
        - h5py
        - scikit-learn
        - pip
        - pip:
                - tensorflow
